version: '3.8'
services:
  database:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  backend:
    build: 
      context: ./
      dockerfile: rust.dockerfile
    container_name: url_shortener
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/postgres
    restart: always
    working_dir: /app

volumes:
  postgres_data:
